config/routes.rb
Rails.application.routes.draw do

  root :to => 'site/site#index'

  
  namespace :admin do
    resources :bars, path: '/bars', only: [:show, :edit, :update] do
      resources :package, path: '/package', module: 'bars'
    end

    
    root :to => 'admin#index'
  end
  
  devise_for :bars, path: "admin/auth_bar", 
    controllers: { sessions: "admin/bars/sessions", registrations: 'admin/bars/registrations' },   
    path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', 
        unlock: 'unlock', registration: 'register', sign_up: 'sign_up' } do
    
    authenticated :bar do
      root 'admin/bars#index', as: :authenticated_root #'admin#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'admin/bars/sessions#new', as: :unauthenticated_root
    end
  end

  devise_for :users
  
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'registrations'  => 'registrations#create',  :as => 'register'
        put  'registrations'  => 'registrations#update',  :as => 'update'
        post 'reset_password' => 'password#create',       :as => 'recoverable'
        post 'sessions'       => 'sessions#create',       :as => 'login'
        delete 'sessions'     => 'sessions#logout',       :as => 'logout'
      end
     
      get  'bar/:bar_id'                   => 'bars#get' 
      get  'bars'                          => 'bars#find_near'
      get  'nr_bars'                       => 'bars#count'
      post 'buy_package'                   => 'users#buy_package'
      get  'user'                          => 'users#get'
      get  'user/my_packages_not_consumed' => 'users#my_packages_not_consumed'
      get  'user/my_packages'              => 'users#my_packages'
      post 'user/drink_chopp'              => 'users#drink_chopp'
      get  'packages/search'               => 'packages#search_packages'
      
    end
  end

end

app/views/admin/include_footer_auth.html.erb
<br>
<br>
Rodapé . autenticado

app/views/admin/include_footer_unauth.html.erb
<br>
<br>
Rodapé . NÃO autenticado

app/views/admin/include_header_auth.html.erb
<!-- Navigation -->
			<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<% 		
			if bar_signed_in? then
%>
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/admin">Admin Chopps and Beers</a>
				</div>
				<!-- Top Menu Items -->
				<ul class="nav navbar-right top-nav">
					
					<li class="dropdown">
					
<% 		
						if bar_signed_in? then
%>
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <John Smith><%= image_tag(current_bar.logo, style: "max-height: 50px;", class: "img-thumbnail")%><%=current_bar.name%> <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									 <%= link_to 'Visualizar', admin_bar_path(current_bar)%>
								</li>
								<li>
									 <%= link_to 'Editar', edit_bar_registration_path() %>
								</li>
								<li>
									 <%= link_to 'Logout', destroy_bar_session_path(), method: :delete %>
								</li>
							</ul>
<%
						end
%>
					</li>
				</ul>
				
				<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
				<div class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav side-nav">
						<li class="active">
							<a href="javascript:;" data-toggle="collapse" data-target="#evento-collapse"><i class="fa fa-fw fa-arrows-v"></i> Relatórios <i class="fa fa-fw fa-caret-down"></i></a>
	                        <ul id="evento-collapse" class="collapse">
	                            <li>
	                                x
	                            </li>
	                            <li>
	                            	y
	                            </li>
	                        </ul>
						</li>
						<li class="active">
							<a href="javascript:;" data-toggle="collapse" data-target="#categoria-collapse"><i class="fa fa-fw fa-arrows-v"></i> Pacotes <i class="fa fa-fw fa-caret-down"></i></a>
	                        <ul id="categoria-collapse" class="collapse">
	                            <li>
	                               <%= link_to 'Lista', admin_bar_package_index_path(current_bar) %>	              
	                            </li>
	                            <li>
	                            	<%= link_to 'Novo', new_admin_bar_package_path(current_bar) %>	                            	
	                            </li>
	                        </ul>
						</li>
					</ul>
				</div>
				<!-- /.navbar-collapse -->
				
<%
			 	end 
%>
</nav>

app/views/admin/include_header_unauth.html.erb
  <%= link_to "Sign up", new_bar_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_bar_session_path, :class => 'navbar-link'  %>
  
<br>